### ISSUE TITLE
[Feature]: Rewrite Landing Page

### ISSUE THREAD

**Issue by knht** [zufall-labs/web#16]
### 🌟 Situation

The current iteration of the landing page is in a pretty bad state CSS wise and requires fixing to the point where it's faster to simply rewrite the website from scratch.

### 🎯 Task

I'd like to see the landing page rewritten with good and extensible styling source code.

### 🛠️ Action

Take the existing code base as a frame of reference but apply best practices while rewriting.

### 🏆 Result

A finished implementation of our Figma landing page design with good source code that is maintainable and extensible.

### 🙋‍♀️ Are you willing to contribute to this feature?

Yes, I'm ready to contribute!

### 📝 Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by knht** [comment]
Desktop mind size auf 1200 machen
Tablet tag (mobile bis 1200 machen)
widget ordentlich einbinden
Zeug in eigene files auslagern
ultra mini mobile tag
scroll bar vereinheitlichen
footer

**Comment by knht** [comment]
Bottom left information widget: left copyright right random quote

**Comment by Colin23** [comment]
New "bug":
On mobile and tablet view the issue widget can't be properly scrolled in. When scrolling on that resolution, the whole page gets scrolled.

**Comment by knht** [comment]
> New "bug": On mobile and tablet view the issue widget can't be properly scrolled in. When scrolling on that resolution, the whole page gets scrolled.

Resolved
