### ISSUE TITLE
[Feature]: Add SSR with issue data fetching and finish the website styling

### ISSUE THREAD

**Issue by Colin23** [zufall-labs/web#6]
### 🌟 Situation

After merging https://github.com/zufall-labs/web/pull/12, there will only be a basic `Svelte` project be set up.

### 🎯 Task

The task is to refine the project, add issue data fetching and finish styling the website.

### 🛠️ Action

Build on top of the existing project, check the GitHub Docs for how the API and the issue data fetching works and make the website styling dynamic and viewable on all screen sizes.

### 🏆 Result

The finished landing page website.

### 🙋‍♀️ Are you willing to contribute to this feature?

Yes, I'll do it!

### 📝 Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by knht** [comment]
Update 20.08.2024: No progress, should be done within 2 weeks.

**Comment by knht** [comment]
@RichardWeller Update?

**Comment by Colin23** [comment]
Still missing:
- GitHub integration 
   - styling 
   - fetching per API only returns the user stories of the user who sends the request
- Mobile styling
- Texts instead of placeholder
- Fine tuning
- General code quality (comments, ...)
